/* eslint-disable @typescript-eslint/no-misused-promises */
import Head from "next/head";
import { useForm } from "react-hook-form";

import { api } from "~/utils/api";

export default function Home() {
  const login = api.main.login.useMutation()
  const {
    register,
    handleSubmit
  } = useForm<any>()

  const onSubmit = async (data: any) => {
    const result = await login.mutateAsync(data)
    console.log(result)
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={handleSubmit(onSubmit)}>
          <input {...register('login')} placeholder="login" />
          <input {...register('password')} placeholder="password" type="password" />
          <button type="submit">submit</button>
        </form>
      </main>
    </>
  );
}
