/* eslint-disable @typescript-eslint/no-misused-promises */
import Head from "next/head";
import { useRouter } from "next/router";
import { useCookies } from 'react-cookie';
import { useForm } from "react-hook-form";
import { UnauthedComponent } from "~/components/AuthedComponent";
import { api } from "~/utils/api";

export default UnauthedComponent(function Home() {
  const [cookies, setCookie, removeCookie] = useCookies();
  const router = useRouter()

  const login = api.main.login.useMutation()
  const {
    register,
    handleSubmit
  } = useForm<any>()

  const onSubmit = async (data: any) => {
    const result = await login.mutateAsync(data)
    setCookie('token', result.token)
    console.log(result)
    if (result.success) {
      void router.push('/private')
    }
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={handleSubmit(onSubmit)}>
          <input {...register('login')} placeholder="login" />
          <input {...register('password')} placeholder="password" type="password" />
          <button type="submit">submit</button>
        </form>
      </main>
    </>
  );
})